version: '3.8'

services:
  api-registrarcliente:
    build: 
      context: ./registrarcliente
      dockerfile: Dockerfile
    image: microservicio-cliente:latest
    ports:
      - "8080:8080"
    restart: always