apiVersion: v1
kind: Service
metadata:
  name: registrarcliente-service
spec:
  type: NodePort  # Cambias LoadBalancer por NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # Puerto público que usará tu profesor
  selector:
    app: registrarcliente  # Asegúrate de que coincida con el tag de tu deployment
